name: On Push Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule: ## Runs every 2 hours
    - cron: '0 */2 * * *'
  
env:
  DEVOPS_DIR: UpdateNRKRssFeed

jobs:
  UpdateRssFeed:
    name: Update Rss feed
    runs-on: ubuntu-latest
    steps:
    - name: Check-out script repository
      uses: actions/checkout@v3
      with:
        repository: VebjornRiiser/UpdateNrkRssFeed
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.DEVOPS_DIR }}

    - name: CreateRSS
      run: |
        python ${{ env.DEVOPS_DIR }}/create_rss.py
        pwd
        ls
      shell: sh
    
    - name: ShowResults
      run: |
        pwd
        ls
        cat abels_taarn.rss
      
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        repository: "/home/runner/work/VebjornRiiser.github.io/VebjornRiiser.github.io"
      # with:
      #   add_options: '-A'
        # if: steps.auto-commit-action.outputs.changes_detected == 'true'
        # run: |
        #   echo "Got Changes!"
        #   ls


