name: On Push Run

on:
  push:
    branches: [ master ]
  #pull_request:
    #branches: [ master ]
  #schedule: ## Runs every 2 hours
    #- cron: '0 */2 * * *'
  
env:
  DEVOPS_DIR: UpdateNRKRssFeed

jobs:
  UpdateRssFeed:
    name: Update Rss feed
    runs-on: ubuntu-latest
    steps:
    - name: Check-out script repository
      uses: actions/checkout@v3

    - name: CreateRssFiles
      run: |
        cd rss
        python ../scripts/CreateNrkRssFeed.py
      shell: sh
    
    - name: ShowResults
      run: |
        cd rss
        pwd
        ls
      
    - uses: stefanzweifel/git-auto-commit-action@v4


